export const DEMO_EMAILS = ['demo@adflow.com', 'creator@adflow.com'];

export const isDemoEmail = (email) => {
  if (!email) return false;
  return DEMO_EMAILS.includes(String(email).toLowerCase());
};

export const demoChannels = [
  {
    id: 'demo-ch-crypto-alpha-signals',
    nombre: 'Crypto Alpha Signals',
    plataforma: 'telegram',
    tematica: 'cripto',
    audiencia: 120000,
    engagement: 2.9,
    ctr: 3.2,
    cpc: 1.25,
    precio: 450,
    moneda: 'EUR',
    estado: 'ACTIVE',
    verificado: true,
    url: 'https://t.me/cryptoalphasignals',
  },
  {
    id: 'demo-ch-startup-weekly',
    nombre: 'Startup Weekly',
    plataforma: 'newsletter',
    tematica: 'negocios',
    audiencia: 45000,
    engagement: 3.6,
    ctr: 2.7,
    cpc: 1.6,
    precio: 220,
    moneda: 'EUR',
    estado: 'ACTIVE',
    verificado: true,
    url: 'https://startupweekly.example.com',
  },
  {
    id: 'demo-ch-gaming-deals-hub',
    nombre: 'Gaming Deals Hub',
    plataforma: 'discord',
    tematica: 'gaming',
    audiencia: 150000,
    engagement: 4.1,
    ctr: 3.9,
    cpc: 0.95,
    precio: 650,
    moneda: 'EUR',
    estado: 'ACTIVE',
    verificado: false,
    url: 'https://discord.gg/gamingdeals',
  },
  {
    id: 'demo-ch-ai-insider-pro',
    nombre: 'AI Insider Pro',
    plataforma: 'telegram',
    tematica: 'tecnologia',
    audiencia: 220000,
    engagement: 3.2,
    ctr: 3.4,
    cpc: 1.8,
    precio: 1200,
    moneda: 'EUR',
    estado: 'ACTIVE',
    verificado: true,
    url: 'https://t.me/aiinsiderpro',
  },
  {
    id: 'demo-ch-trading-elite-club',
    nombre: 'Trading Elite Club',
    plataforma: 'telegram',
    tematica: 'negocios',
    audiencia: 400000,
    engagement: 2.4,
    ctr: 2.2,
    cpc: 2.4,
    precio: 2500,
    moneda: 'EUR',
    estado: 'ACTIVE',
    verificado: true,
    url: 'https://t.me/tradingeliteclub',
  },
  {
    id: 'demo-ch-latam-growth-playbook',
    nombre: 'LatAm Growth Playbook',
    plataforma: 'whatsapp',
    tematica: 'negocios',
    audiencia: 28000,
    engagement: 5.2,
    ctr: 4.5,
    cpc: 0.85,
    precio: 140,
    moneda: 'EUR',
    estado: 'ACTIVE',
    verificado: false,
    url: 'https://wa.me/00000000000',
  },
  {
    id: 'demo-ch-health-reset-lab',
    nombre: 'Health Reset Lab',
    plataforma: 'instagram',
    tematica: 'salud',
    audiencia: 87000,
    engagement: 3.8,
    ctr: 3.0,
    cpc: 1.35,
    precio: 320,
    moneda: 'EUR',
    estado: 'ACTIVE',
    verificado: true,
    url: 'https://instagram.com/healthresetlab',
  },
  {
    id: 'demo-ch-travel-lux-escapes',
    nombre: 'Travel Lux Escapes',
    plataforma: 'instagram',
    tematica: 'viajes',
    audiencia: 260000,
    engagement: 2.7,
    ctr: 2.6,
    cpc: 2.1,
    precio: 980,
    moneda: 'EUR',
    estado: 'ACTIVE',
    verificado: true,
    url: 'https://instagram.com/travelluxescapes',
  },
  {
    id: 'demo-ch-devs-productivity-notes',
    nombre: 'Devs Productivity Notes',
    plataforma: 'telegram',
    tematica: 'tecnologia',
    audiencia: 32000,
    engagement: 4.6,
    ctr: 3.8,
    cpc: 0.9,
    precio: 190,
    moneda: 'EUR',
    estado: 'ACTIVE',
    verificado: false,
    url: 'https://t.me/devsproductivitynotes',
  },
  {
    id: 'demo-ch-fintech-insights-daily',
    nombre: 'Fintech Insights Daily',
    plataforma: 'facebook',
    tematica: 'negocios',
    audiencia: 310000,
    engagement: 2.2,
    ctr: 2.4,
    cpc: 2.25,
    precio: 1400,
    moneda: 'EUR',
    estado: 'ACTIVE',
    verificado: true,
    url: 'https://facebook.com/fintechinsightsdaily',
  },
  {
    id: 'demo-ch-fashion-curators-club',
    nombre: 'Fashion Curators Club',
    plataforma: 'instagram',
    tematica: 'moda',
    audiencia: 24000,
    engagement: 4.9,
    ctr: 3.6,
    cpc: 1.1,
    precio: 120,
    moneda: 'EUR',
    estado: 'ACTIVE',
    verificado: false,
    url: 'https://instagram.com/fashioncuratorsclub',
  },
  {
    id: 'demo-ch-crypto-brief-latam',
    nombre: 'Crypto Brief LatAm',
    plataforma: 'telegram',
    tematica: 'cripto',
    audiencia: 78000,
    engagement: 3.0,
    ctr: 2.9,
    cpc: 1.4,
    precio: 310,
    moneda: 'EUR',
    estado: 'ACTIVE',
    verificado: true,
    url: 'https://t.me/cryptobrieflatam',
  },
];

export const demoAdvertiserDashboard = {
  stats: {
    resumen: {
      totalInversion: 620.0,
      anunciosActivos: 3,
      totalAnuncios: 7,
      ctr: 3.1,
      impresionesTotales: 42850,
    },
    anunciosPorEstado: {
      activo: 3,
      pendiente: 2,
      completado: 2,
    },
  },
  activeAds: [
    {
      _id: 'demo-ad-1',
      title: 'Lanzamiento SaaS B2B - Q2',
      category: 'negocios',
      tracking: { impresiones: 18540 },
      budget: 240.0,
      estado: 'activo',
      canalId: { name: 'Startup Weekly' },
    },
    {
      _id: 'demo-ad-2',
      title: 'Promo AI Toolkit',
      category: 'tecnologia',
      tracking: { impresiones: 22110 },
      budget: 320.0,
      estado: 'activo',
      canalId: { name: 'AI Insider Pro' },
    },
    {
      _id: 'demo-ad-3',
      title: 'Gaming Bundle Weekend',
      category: 'gaming',
      tracking: { impresiones: 14630 },
      budget: 180.0,
      estado: 'activo',
      canalId: { name: 'Gaming Deals Hub' },
    },
  ],
  allAds: [
    {
      _id: 'demo-ad-1',
      title: 'Lanzamiento SaaS B2B - Q2',
      category: 'negocios',
      tracking: { impresiones: 18540 },
      budget: 240.0,
      estado: 'activo',
      canalId: { name: 'Startup Weekly' },
    },
    {
      _id: 'demo-ad-2',
      title: 'Promo AI Toolkit',
      category: 'tecnologia',
      tracking: { impresiones: 22110 },
      budget: 320.0,
      estado: 'activo',
      canalId: { name: 'AI Insider Pro' },
    },
    {
      _id: 'demo-ad-3',
      title: 'Gaming Bundle Weekend',
      category: 'gaming',
      tracking: { impresiones: 14630 },
      budget: 180.0,
      estado: 'activo',
      canalId: { name: 'Gaming Deals Hub' },
    },
    {
      _id: 'demo-ad-4',
      title: 'Oferta Fintech Premium',
      category: 'negocios',
      tracking: { impresiones: 9800 },
      budget: 1400.0,
      estado: 'completado',
      canalId: { name: 'Fintech Insights Daily' },
    },
    {
      _id: 'demo-ad-5',
      title: 'Campaña Travel Luxury',
      category: 'viajes',
      tracking: { impresiones: 11220 },
      budget: 980.0,
      estado: 'pendiente',
      canalId: { name: 'Travel Lux Escapes' },
    },
  ],
  recentActivities: [
    { content: 'Tu anuncio “Promo AI Toolkit” fue aprobado', timestamp: 'Hace 2h', type: 'aprobacion' },
    { content: 'Nuevo canal verificado disponible en Tecnología', timestamp: 'Ayer', type: 'info' },
    { content: 'Tu campaña “Gaming Bundle Weekend” alcanzó 10k impresiones', timestamp: 'Hace 2 días', type: 'info' },
  ],
};

export const demoCreatorDashboard = {
  stats: {
    resumen: {
      totalIngresos: 870.0,
      totalAnunciosRecibidos: 8,
      canalesActivos: 3,
      totalCanales: 3,
      ingresosPendientes: 240.0,
    },
    canalesPorPlataforma: {
      Telegram: 2,
      Discord: 1,
    },
  },
  ads: [
    {
      _id: 'demo-cr-ad-1',
      title: 'Review herramienta IA',
      budget: 320.0,
      estado: 'pendiente',
      canalId: { name: 'AI Insider Pro' },
    },
    {
      _id: 'demo-cr-ad-2',
      title: 'Oferta trading premium',
      budget: 450.0,
      estado: 'activo',
      canalId: { name: 'Crypto Alpha Signals' },
    },
    {
      _id: 'demo-cr-ad-3',
      title: 'Patrocinio newsletter B2B',
      budget: 220.0,
      estado: 'completado',
      canalId: { name: 'Startup Weekly' },
    },
    {
      _id: 'demo-cr-ad-4',
      title: 'Promo fitness curso',
      budget: 320.0,
      estado: 'completado',
      canalId: { name: 'Health Reset Lab' },
    },
    {
      _id: 'demo-cr-ad-5',
      title: 'Campaña fintech insights',
      budget: 1400.0,
      estado: 'activo',
      canalId: { name: 'Fintech Insights Daily' },
    },
    {
      _id: 'demo-cr-ad-6',
      title: 'Lanzamiento travel package',
      budget: 980.0,
      estado: 'pendiente',
      canalId: { name: 'Travel Lux Escapes' },
    },
  ],
  channels: [
    { _id: 'demo-own-1', name: 'AI Insider Pro', platform: 'Telegram', status: 'Activo' },
    { _id: 'demo-own-2', name: 'Crypto Brief LatAm', platform: 'Telegram', status: 'Activo' },
    { _id: 'demo-own-3', name: 'Gaming Deals Hub', platform: 'Discord', status: 'Activo' },
  ],
  recentActivities: [
    { content: 'Tienes 2 solicitudes de anuncios pendientes', timestamp: 'Hoy', type: 'anuncio' },
    { content: 'Pago procesado por “Patrocinio newsletter B2B”', timestamp: 'Ayer', type: 'pago' },
    { content: 'Nuevo anunciante guardó tu canal en favoritos', timestamp: 'Hace 3 días', type: 'info' },
  ],
};
